[workspace]
members = ["verifier", "example/fibonacci-program", "example/script"]
resolver = "2"

[workspace.dependencies]
# sp1-verifier = { version = "5.2.1", default-features = false }
# sp1-sdk = { version = "5.2.1" }
# sp1-zkvm = { version = "5.2.1" }
# sp1-build = { version = "5.2.1" }

# Until the relevant feature is published on crates.io:

sp1-sdk = { git = "https://github.com/succinctlabs/sp1-wip.git", rev = "826251eb0a7cdbb5ae9d66c399aace74f0da8c3d" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1-wip.git", rev = "826251eb0a7cdbb5ae9d66c399aace74f0da8c3d" }
sp1-build = { git = "https://github.com/succinctlabs/sp1-wip.git", rev = "826251eb0a7cdbb5ae9d66c399aace74f0da8c3d" }
sp1-verifier = { git = "https://github.com/succinctlabs/sp1-wip.git", rev = "826251eb0a7cdbb5ae9d66c399aace74f0da8c3d", default-features = false }
